databases:
- name: nextcloud
  postgresMajorVersion: "16"
  plan: starter
  ipAllowList: []


services:
- type: redis
  name: nc-redis
  ipAllowList: []
  
- type: web
  plan: standard
  name: nc-minio-server
  healthCheckPath: /minio/health/live
  runtime: image
  image:
    url: minio/minio:latest
  dockerCommand: minio server /data --address $HOST:$PORT --console-address $HOST:$CONSOLE_PORT
  autoDeploy: false
  disk:
    name: data
    sizeGB: 12
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: 9000
  - key: CONSOLE_PORT
    value: 9090

- type: web
  plan: starter
  name: nc-minio-console
  runtime: docker
  dockerContext: ./console
  dockerfilePath: ./console/Dockerfile
  envVars:
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: 10000
  - key: MINIO_HOST
    fromService:
      name: nc-minio-server
      type: web
      property: host
  - key: MINIO_CONSOLE_PORT
    fromService:
      name: nc-minio-server
      type: web
      envVarKey: CONSOLE_PORT

- type: web
  plan: standard
  name: nextcloud
  # runtime: image
  runtime: docker
  dockerContext: ./nextcloud
  dockerfilePath: ./nextcloud/Dockerfile
  # image:
    # url: nextcloud:latest
  disk:
    name: data
    sizeGB: 13
    mountPath: /var/www/html
  envVars:
  - key: POSTGRES_HOST
    fromDatabase:
      name: nextcloud
      property: host
  - key: POSTGRES_DB
    fromDatabase:
      name: nextcloud
      property: database
  - key: POSTGRES_USER
    fromDatabase:
      name: nextcloud
      property: user
  - key: POSTGRES_PASSWORD
    fromDatabase:
      name: nextcloud
      property: password
  - key: NEXTCLOUD_ADMIN_USER
    value: admin
  - key: NEXTCLOUD_ADMIN_PASSWORD
    generateValue: true
  # - key: NEXTCLOUD_DATA_DIR
  #   value: /var/www/html/data
  - key: NEXTCLOUD_INIT_HTACCESS
    value: "true"
  - key: REDIS_HOST
    fromService:
      name: nc-redis
      type: redis
      property: host
  - key: REDIS_HOST_PORT
    fromService:
      name: nc-redis
      type: redis
      property: port
  # - key: SMTP_HOST
  # - key: SMTP_SECURE
  # - key: SMTP_PORT
  # - key: SMTP_AUTHTYPE
  # - key: SMTP_NAME
  # - key: SMTP_PASSWORD
  # - key: MAIL_FROM_ADDRESS
  # - key: MAIL_DOMAIN
  - key: OBJECTSTORE_S3_BUCKET
    value: nextcloud-store
  - key: OBJECTSTORE_S3_HOST
    fromService:
      name: nc-minio-server
      type: web
      property: host
  - key: OBJECTSTORE_S3_PORT
    fromService:
      name: nc-minio-server
      type: web
      envVarKey: PORT
  - key: OBJECTSTORE_S3_KEY
    fromService:
      name: nc-minio-server
      type: web
      envVarKey: MINIO_ROOT_USER
  - key: OBJECTSTORE_S3_SECRET
    fromService:
      name: nc-minio-server
      type: web
      envVarKey: MINIO_ROOT_PASSWORD
  - key: OBJECTSTORE_S3_SSL
    value: "false"
  - key: OBJECTSTORE_S3_OBJECT_PREFIX
    value: "nextcloud"
  - key: OBJECTSTORE_S3_USEPATH_STYLE
    value: "true"
  - key: OBJECTSTORE_S3_AUTOCREATE
    value: "true"
  - key: PORT
    value: 80
